### ISSUE TITLE
Versioning in the Windows binary

### ISSUE THREAD

**Issue by andypiper** [smaeda-ks/tw-oob-oauth-cli#1]
I can clearly see that this line sets the version to 1.0.2 
https://github.com/smaeda-ks/tw-oob-oauth-cli/blob/c81be0ba3aea36bf3d23f445f279812876921ab3/src/main.go#L44

However, in the Windows AMD64 binary I downloaded, the -h flag reports this as version 1.0.0 - is this a bug upstream in the CLI library, or an issue with the release downloads?

**Comment by smaeda-ks** [comment]
@andypiper !!! Thanks for flagging this. Yes, it was my mistake... I've updated the download packages: https://github.com/smaeda-ks/tw-oob-oauth-cli/releases/tag/v1.0.2
